project:
  type: book

book:
  title: "Corso di R: dalle basi alla prima analisi dei dati"
  author: 
    # - name: Andrea Bisignano
    #   affiliation: [arpal]
    - name: Andrea Bazzano
      orcid: 0000-0002-9353-3919
      affiliation: 
      - id: arpal
        name: Agenzia regionale per la protezione dell'ambiente ligure (ARPAL)
  reader-mode: true
  favicon: favicon.png
  site-url: missing
  repo-url: missing
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: basics.qmd
      chapters: 
        - start.qmd
        - objects.qmd
        - transform.qmd
format:
  html:
    theme: cosmo
    lightbox: true
    fig-dpi: 72

    author-meta: "Andrea Bisignano, Andrea Bazzano"
    callout-appearance: simple
lang: it

