# Le basi {#sec-basics-intro .unnumbered}

```{r}
#| echo: false
source("_common.R")
```

Questa parte introduce i concetti fondamentali per iniziare a lavorare con R in modo efficace e autonomo. Nei due capitoli che seguono, si partirà dalle prime semplici operazioni nella console per familiarizzare con l'ambiente di lavoro e la sintassi di R, fino a comprendere la natura degli oggetti e dei dati con cui si lavorerà.

Questa parte è suddivisa in tre capitoli così organizzati:

- [nel capitolo 2](#sec-basics) si utilizzerà a usare la console di R, organizzando il codice in script e consultare l'aiuto in linea;
- [nel capitolo 3](#sec-objects) si impareranno i tipi di dati fondamentali in R e le principali classi di oggetti;
- [nel capitolo 4](#sec-coding) si studieranno alcuni costrutti elementari per iniziare a programmare con R.

Questi argomenti costituiscono le fondamenta indispensabili per affrontare con sicurezza le analisi e le manipolazioni di dati più complesse che saranno presentate nei capitoli successivi.